// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'card': string;
  'cardImage': string;
  'cardStats': string;
  'cardStatsData': string;
  'cardStatsItem': string;
  'cardTypes': string;
  'cardTypesData': string;
  'cardTypesDataGrass': string;
  'cardTypesDataPoison': string;
  'cardTypesTitle': string;
}
export const cssExports: CssExports;
export default cssExports;
