// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'homePage': string;
  'homePageContent': string;
  'homePageDescription': string;
  'homePageFooter': string;
  'homePageHeading': string;
  'homePageLink': string;
  'homePageParallax': string;
  'homePageWrapper': string;
}
export const cssExports: CssExports;
export default cssExports;
