// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'logo': string;
  'logoImage': string;
}
export const cssExports: CssExports;
export default cssExports;
