// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'heading': string;
  'headingFontSizeL': string;
  'headingFontSizeM': string;
  'headingFontSizeS': string;
  'headingFontSizeXl': string;
  'headingFontSizeXs': string;
  'headingFontSizeXxl': string;
  'headingFontWeightBold': string;
  'headingFontWeightNormal': string;
}
export const cssExports: CssExports;
export default cssExports;
