// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'header': string;
  'headerLogo': string;
  'headerMenuList': string;
  'headerNavigation': string;
  'headerNavigationOpened': string;
  'headerOpenMenuButton': string;
}
export const cssExports: CssExports;
export default cssExports;
