// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'pageLayout': string;
  'pageLayoutFooter': string;
  'pageLayoutHome': string;
}
export const cssExports: CssExports;
export default cssExports;
